import click
import toml
import os
import subprocess
import sys
import shutil
from pathlib import Path

VERSION = "0.3.2-alpha"

# モデル名とRustクレートの対応表 (当面はハードコード)
SOLVER_MAP = {
    "wave_equation_2d": "raw-pinn-engine", 
    "heat_equation": "heat-equation",
    "lorenz_ode": "lorenz-ode",
    "generated_mlp": "generated-mlp",
    "cnn_model": "generated-cnn",
    "cnn_v04": "cnn-v04",
    "fno_model": "fno-v0",
    "split_wave": "split-wave",
    "cnn_quantized": "cnn-quantized"
}

@click.group()
@click.version_option(version=VERSION)
def main():
    """Dyne: Universal Physics Container Toolchain"""
    pass

@main.command()
@click.option('--config', '-c', default='dyne.toml', help='Path to config file')
def run(config):
    """Build and Run the simulation defined in dyne.toml"""
    
    # --- 1. 設定読み込み ---
    config_path = Path(config).resolve()
    project_root = config_path.parent
    
    if not config_path.exists():
        click.secho(f"Error: Configuration file '{config_path}' not found.", fg="red")
        sys.exit(1)

    try:
        with open(config_path, "r", encoding="utf-8") as f:
            conf = toml.load(f)
    except Exception as e:
        click.secho(f"Error parsing TOML: {e}", fg="red")
        sys.exit(1)

    project_name = conf.get("project", {}).get("name", "Unknown")
    model_name = conf.get("simulation", {}).get("model", "")

    click.secho(f"\n🚀 Starting Dyne Runtime v{VERSION}", fg="green", bold=True)
    click.echo(f"   📂 Project: {project_name}")
    click.echo(f"   🧮 Model:   {model_name}")

    # --- 2. Rustソルバの特定 ---
    solver_crate = SOLVER_MAP.get(model_name)
    if not solver_crate:
        click.secho(f"Error: Model '{model_name}' is not supported yet.", fg="red")
        click.echo(f"Available models: {', '.join(SOLVER_MAP.keys())}")
        sys.exit(1)

    # Dyneルートディレクトリの特定 (cli.pyの2つ上と仮定)
    # cli.py -> dyne/ -> Dyne/ (Root)
    dyne_root = Path(__file__).parent.parent
    solver_path = dyne_root / "rust" / "solvers" / solver_crate

    if not solver_path.exists():
        click.secho(f"Error: Solver crate not found at {solver_path}", fg="red")
        sys.exit(1)

    # --- 3. パラメータ注入処理 ---
    click.secho(f"\n💉 Injecting parameters into {solver_crate}...", fg="yellow")

    sim_config = conf.get("simulation", {})
    # デフォルト値を設定
    width = sim_config.get("width", 512)
    height = sim_config.get("height", 512)
    dt = sim_config.get("dt", 0.05)
    
    # Rustコード生成 (constants.rs)
    constants_code = f"""// Generated by Dyne Compiler. DO NOT EDIT.
pub const WIDTH: usize = {width};
pub const HEIGHT: usize = {height};
pub const DT: f32 = {dt};
"""

    constants_path = solver_path / "src" / "constants.rs"
    try:
        with open(constants_path, "w", encoding="utf-8") as f:
            f.write(constants_code)
        click.echo(f"   📄 Generated: {constants_path.name} (W={width}, DT={dt})")
    except Exception as e:
        click.secho(f"Error generating code: {e}", fg="red")
        sys.exit(1)

    # --- 4. ビルド実行 (wasm-pack) ---
    click.secho(f"\n🔨 Building solver: {solver_crate} ...", fg="yellow")
    
    # 出力先: 実行ディレクトリ配下の ./pkg
    output_dir = project_root / "pkg"
    
    # ビルドコマンド
    # wasm-pack build <solver_path> --target web --out-dir <output_dir>
    cmd = [
        "wasm-pack", "build", str(solver_path),
        "--target", "web",
        "--out-dir", str(output_dir),
        "--no-typescript" # 今回はJSのみで簡略化
    ]

    try:
        subprocess.run(cmd, check=True)
        click.secho("✅ Build successful!", fg="green")
    except subprocess.CalledProcessError:
        click.secho("❌ Build failed.", fg="red")
        sys.exit(1)
    except FileNotFoundError:
        click.secho("❌ Error: 'wasm-pack' command not found. Please install it.", fg="red")
        sys.exit(1)

    # --- 5. サーバー起動 ---
    server_port = 8000
    click.secho(f"\n🌍 Serving at http://localhost:{server_port}", fg="cyan")
    click.echo("   (Press CTRL+C to stop)")
    
    try:
        subprocess.run(
            [sys.executable, "-m", "http.server", str(server_port)],
            cwd=project_root
        )
    except KeyboardInterrupt:
        click.echo("\n🛑 Server stopped.")

if __name__ == "__main__":
    main()